services:
 bank-core:
  build:
   context: .
   dockerfile: ./bank-core/Dockerfile
  ports:
   - '3000:3000'
  environment:
   - DATABASE_URL=mongodb://mongodb:27017/banking-demo
   - APP_PORT_1=3000
   - MONGO_URL=mongodb://mongodb:27017/testdb
   - JWT_SECRET=${JWT_SECRET}
  depends_on:
   - mongodb

 websocket:
  build:
   context: .
   dockerfile: ./websocket/Dockerfile
  ports:
   - '3000:3000'
  environment:
   - APP_PORT_2=3001
   - WS_PORT=8080
   - JWT_SECRET=${JWT_SECRET}
  depends_on:
   - mongodb

 mongodb:
  container_name: mongodb
  image: mongo:latest
  ports:
   - '27017:27017'
  volumes:
   - ./mongodb_data:/data/db

networks:
 default:
  name: banking-demo-network
